### ISSUE TITLE
Not work in Ionic/Vue

### ISSUE THREAD

**Issue by damianlluch** [JacobDB/ios-install-prompt#14]
Hi, thanks for sharing this resources.

I try with your library in my project and not work.

I execute the code ni mounted() in Vue.

........................................................
<ion-content>
  <div class="pwa-install-prompt__container">
    .......
  </div>
</ion-content>
......................................................................
<script>
  import pwaInstallPrompt from "pwa-install-prompt";
  .....
  ....
 mounted() {
    new pwaInstallPrompt(".pwa-install-prompt__container", {
      ..............
    });

--------------------------------------
thanks!

![image](https://user-images.githubusercontent.com/1463804/77905917-5aef3900-7287-11ea-8e23-df0516c01cc8.png)

**Comment by JacobDB** [comment]
Seems like you may just need to import the CSS.
